"""empty message

Revision ID: 78e085948577
Revises: 6924b7d31561
Create Date: 2023-03-21 16:25:30.659915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e085948577'
down_revision = '6924b7d31561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('item_type', sa.String(
                        length=20), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('item_location',
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.Column('location_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['item_id'], ['location.id'], ),
                    sa.ForeignKeyConstraint(['location_id'], ['item.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_location')
    # ### end Alembic commands ###
