"""empty message

Revision ID: c03d1edbba01
Revises: 78e085948577
Create Date: 2023-03-21 17:07:10.212159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03d1edbba01'
down_revision = '78e085948577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('item',
    #                 sa.Column('id', sa.Integer(), nullable=False),
    #                 sa.Column('item_type', sa.String(
    #                     length=20), nullable=False),
    #                 sa.PrimaryKeyConstraint('id')
    #                 )
    # op.drop_table('accepted_item')
    with op.batch_alter_table('accepted_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'location', ['item_id'], ['id'])
        batch_op.create_foreign_key(None, 'item', ['location_id'], ['id'])
        batch_op.drop_column('accepted_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accepted_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_item_id',
                            sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            None, 'location', ['accepted_item_id'], ['id'])
        batch_op.create_foreign_key(None, 'accepted_item', [
                                    'location_id'], ['id'])
        batch_op.drop_column('item_id')

    op.create_table('accepted_item',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('item_type', sa.VARCHAR(
                        length=20), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('item')
    # ### end Alembic commands ###
